### ISSUE TITLE
MINISTRA TV PLATFORM 5.4.1

### ISSUE THREAD

**Issue by richiebob2015** [SlaSerX/stalker#16]
https://wiki.infomir.eu/eng/ministra-tv-platform/changelog/ministra-tv-platform-5-4/ministra-tv-platform-5-4-1

Please can you update to 5.4.1?

Thanks again your awesome :)

**Comment by SlaSerX** [comment]
done :)

**Comment by richiebob2015** [comment]
wow u rock dude!!
