### ISSUE TITLE
can't login after install

### ISSUE THREAD

**Issue by thaidh1907** [SlaSerX/stalker#20]
I install on Ubuntu 16.04
![image](https://user-images.githubusercontent.com/3184283/42997126-d1062890-8c3f-11e8-9870-477fcee663b7.png)

i can't login with admin/1
![image](https://user-images.githubusercontent.com/3184283/42996659-6b1ae314-8c3e-11e8-93ff-c800949e46c9.png)

**Comment by SlaSerX** [comment]
u dont enter mysql password try

cd /var/www/html/stalker_portal/deploy

sudo phing

and when ask u Enter password just type "st@lk3r"
