### ISSUE TITLE
Tariff plan to user

### ISSUE THREAD

**Issue by shamar112** [SlaSerX/stalker#24]
Cannot assign a tariff plan to a user

**Comment by sp0okz** [comment]
Make sure you have enabled it - enable_tariff_plans = true

**Comment by SlaSerX** [comment]
Also that is script for clean installing all custom which u need u can find
on manual and setup

На вт, 30.10.2018 г., 16:18 sp0okz <notifications@github.com> написа:

**Comment by shamar112** [comment]
when i enable tariff, and set it on and load the portal on a mag it just loads in a loop cannot sign in just a icon repeating, but when i disable tariff and delete the config.ini the portal loads on the device i even tried it on stb emu and a mag device

**Comment by shamar112** [comment]
also the bottom icons on the ministra themes does not show it only show and "x" for each icon like e.g list, epg, view icons

**Comment by SlaSerX** [comment]
Read manual on infomir

На чт, 6.12.2018 г., 19:34 shamar112 <notifications@github.com написа:
