### ISSUE TITLE
 Connecting to linuxhelps.net 

### ISSUE THREAD

**Issue by penfolduk** [SlaSerX/stalker#25]
--2018-11-23 17:31:10--  (try: 6)  http://linuxhelps.net/configs/000-default.conf
Connecting to linuxhelps.net (linuxhelps.net)..
Connecting to linuxhelps.net failed: Connection timed out.

**Comment by penfolduk** [comment]
looks like DNS issue your end

**Comment by penfolduk** [comment]
gives up after 20 tries

**Comment by penfolduk** [comment]
same with stalker portal

**Comment by penfolduk** [comment]
Resolving lab.itbox.bg (lab.itbox.bg)... 5.104.177.220
Connecting to lab.itbox.bg (lab.itbox.bg)|5.104.177.220|:80... failed: Connection timed out.
Retrying.

**Comment by SlaSerX** [comment]
I dont have problem with dns :) try to check your connections to Bulgaria

На пт, 23.11.2018 г., 18:32 penfolduk <notifications@github.com написа:

**Comment by penfolduk** [comment]
im trying to install  on a VPS server

**Comment by penfolduk** [comment]
i get 404 from http://linuxhelps.net/configs

**Comment by penfolduk** [comment]
but https://linuxhelps.net/configs/000-default.conf works

**Comment by penfolduk** [comment]
--2018-11-24 18:00:14--  https://linuxhelps.net/configs/000-default.conf
Resolving linuxhelps.net (linuxhelps.net)... 91.215.216.12
Connecting to linuxhelps.net (linuxhelps.net)|91.215.216.12|:443... failed: Connection timed out.
Retrying.

**Comment by SlaSerX** [comment]
Just check connection to my point :)

На сб, 24.11.2018 г., 18:50 penfolduk <notifications@github.com написа:

**Comment by penfolduk** [comment]
no ping to 91.215.216.12

**Comment by penfolduk** [comment]
time out on http://lab.itbox.bg/software/tv/ministra-5.5.0.zip now

**Comment by penfolduk** [comment]
--2018-11-24 22:48:59--  (try: 2)  http://lab.itbox.bg/software/tv/vendor.tar
Connecting to lab.itbox.bg (lab.itbox.bg)|5.104.177.220|:80... failed: Connection timed out.
Retrying.

**Comment by SlaSerX** [comment]
Check your dns and add google dns :)

На сб, 24.11.2018 г., 22:53 penfolduk <notifications@github.com написа:

**Comment by penfolduk** [comment]
http://lab.itbox.bg/software/tv/vendor.tar fails on remote vps and my home pc

**Comment by penfolduk** [comment]
do you have another url where vendar.tar is?

**Comment by josh2893** [comment]
Im using google dns  8.8.8.8 and 8.8.4.4

cant connect to http://lab.itbox.bg/software/tv/ministra-5.5.0.zip

http://lab.itbox.bg  seems to be down?

**Comment by josh2893** [comment]
Its back online FYI!!!
