### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by ahgud** [SlaSerX/stalker#29]
https://lab.itbox.bg/software/tv/ministra-5.5.0.zip

**Comment by chuckomat** [comment]
access denied ;-) It checks your IP address and if you start the script a 2nd time - refused

**Comment by chuckomat** [comment]
wget http://lab.itbox.bg/software/tv/vendor.tar
--2019-02-08 15:14:27--  http://lab.itbox.bg/software/tv/vendor.tar
Resolving lab.itbox.bg (lab.itbox.bg)... 5.104.177.220
Connecting to lab.itbox.bg (lab.itbox.bg)|5.104.177.220|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://lab.itbox.bg/software/tv/vendor.tar [following]
--2019-02-08 15:14:27--  https://lab.itbox.bg/software/tv/vendor.tar
Connecting to lab.itbox.bg (lab.itbox.bg)|5.104.177.220|:443... failed: Connection refused.
Resolving lab.itbox.bg (lab.itbox.bg)... 5.104.177.220
Connecting to lab.itbox.bg (lab.itbox.bg)|5.104.177.220|:443... failed: Connection refused.
-------------------------
same for ministra-zip file .
Maybe SlaserX got some claims and has closed the links?

**Comment by Neolo** [comment]
What a b*tch
