### ISSUE TITLE
Not Found URL /stalker_portal 

### ISSUE THREAD

**Issue by techdummy** [SlaSerX/stalker#3]
The requested URL /stalker_portal was not found on this server.

Tried installing it on Ubuntu 16.04 x64 and Ubuntu 17.04 x64 does not work seems that its looking for php5.x and mysql versions that it does not recognize. 

so I tried Ubuntu 14.04 x64 and that installed correctly but when i try to load the portal I get [The requested URL /stalker_portal was not found on this server.]  seems the script is not creating the folder in  (/var/www/)? 

Thanks for your help!

**Comment by SlaSerX** [comment]
Check for dir or if not renamed just rename to stalker_portal :)
