### ISSUE TITLE
script nto working

### ISSUE THREAD

**Issue by apolo56** [SlaSerX/stalker#31]
* Restarting web server apache2                                                                                                                                                  [ OK ]
 * Restarting nginx nginx                                                                                                                                                         [ OK ]
 * Restarting web server apache2                                                                                                                                                  [ OK ]
 * Restarting nginx nginx                                                                                                                                                         [ OK ]
./lab/stalker: line 182: cd: /var/www/html/stalker_portal/deploy: No such file or directory
Buildfile: build.xml does not exist!

new script not working 

ubuntu 14.04

**Comment by SlaSerX** [comment]
script work just link is down but now is updated :) test it

**Comment by apolo56** [comment]
yes i see now 

do you have skype 
i need to talk with you please

**Comment by ahgud** [comment]
> script work just link is down but now is updated :) test it

OMG´! i fucking love you ! <3
I wil try again now

**Comment by SlaSerX** [comment]
givme your skype i will add you
