### ISSUE TITLE
Blank page under Settings tabs

### ISSUE THREAD

**Issue by Mikam74** [SlaSerX/stalker#32]
**Describe the bug**
Ministra 5.5.0

Under Settings tab, Appearance and firmware update option showing blank page when clicked;
Tested with Firefox and with Chrome I get error " This page isn’t working 188.166.30.82 is currently unable to handle this request.
HTTP ERROR 500"

Installed twice on a fresh ubuntu server 16.04 still same.Other than everything else working fine

**Comment by SlaSerX** [comment]
i dont know where u wrong check server log
