### ISSUE TITLE
Minstra Installation failed 

### ISSUE THREAD

**Issue by petarn47** [SlaSerX/stalker#33]
Hello Can you help me install minstra portal on ubuntu.
I bekome somethins error reports. Can you me help with teamviwer.

Thanks

**Comment by satfun100** [comment]
Don't ask him for help he will steal from you like the 150€ he stole from me.....

**Comment by satfun100** [comment]
Keep deleting I'll keep telling everyone you stole from me. You know my Skype contact me....
