### ISSUE TITLE
http://linuxhelps.net/configs/000-default.conf . ERROR

### ISSUE THREAD

**Issue by dph19** [SlaSerX/stalker#34]
Good afternoon all,

Debian 8 fresh install, error whilst trying to connect to the above url, now 20 retries and still the same. Any ideas?

![Captura de pantalla 2019-03-22 a las 13 08 54](https://user-images.githubusercontent.com/48829055/54821827-a994eb00-4ca3-11e9-800e-2f5ec00e8b8b.png)

**Comment by SlaSerX** [comment]
check your internet connections the config files is work correct
