### ISSUE TITLE
BUILD FAILED Debian 8

### ISSUE THREAD

**Issue by skoja** [SlaSerX/stalker#36]
BUILD FAILED @SlaSerX 
/var/www/html/stalker_portal/deploy/build.xml:140:12: /var/www/html/stalker_portal/deploy/build.xml:145:30: Mysql - ERROR 1045 (28000): Access denied for user 'stalker'@'localhost' (using password: YES)

Total time: 50.5075 seconds

**Comment by SlaSerX** [comment]
Yes couse when system ask enter mysql password u dont put

На пт, 21 юни 2019 г., 19:16 skoja <notifications@github.com> написа:
