### ISSUE TITLE
/auth/token api authorization issue

### ISSUE THREAD

**Issue by cclaflin89** [SlaSerX/stalker#38]
This question may out of scope, but just wanted to check if some configuration is missing.

After Ministra 5.5 set up, the stalker_portal dashboard worked fine. But after adding a user, I couldn't authorize via rest API.

POST: /stalker_portal/auth/token
Header content-type: application/x-www-form-urlencoded
grant_type=password&username=myusername&password=mypass

It returns `invalid_grant` and below are details:
{
    "error": "invalid_grant",
    "error_description": "Username or password is incorrect"
}

Any help would be appreciated. Thanks in advance.

**Comment by snake24564** [comment]
I don't think its a configuration issue so just try to contact Infomir eu at: https://www.infomir.eu/eng/support/form/support.php 

They'll help for sure.
