### ISSUE TITLE
ports.conf

### ISSUE THREAD

**Issue by fatoskurtishi** [SlaSerX/stalker#43]
Apache wont start: 
apache2: Syntax error on line 144 of /etc/apache2/apache2.conf: Syntax error on line 5 of /etc/apache2/ports.conf: Expected </meta> but saw </head>

and file ports.conf

```
<html>
<head>
<meta name="robots" content="noarchive" />
<meta name="googlebot" content="nosnippet" />
</head>
<body>
<div align=center>
<h3>Error. Page cannot be displayed. Please contact your service provider for more details.  (27)</h3>
</div>
</body>
</html>
```

**Comment by SlaSerX** [comment]
Yes links is die but now i updated try now :)

На чт, 19.09.2019 г. в 15:51 ч. fatoskurtishi <notifications@github.com>
написа:
