### ISSUE TITLE
Ubuntu 16.04 - Ioncube Error

### ISSUE THREAD

**Issue by LiamKenyon** [SlaSerX/stalker#45]
**Describe the bug**
BUILD FAILED
/var/www/html/stalker_portal/deploy/build.xml:244:183: Could not find file /var/www/html/stalker_portal/deploy/src/ioncube/64/ioncube_loader_lin_7.3.so to copy.

**To Reproduce**
Follow install guide on 16.04

**Comment by SlaSerX** [comment]
sure couse ubuntu 16.04 use php 7.2 not 7.3 check logs or downgrade your php version

**Comment by SlaSerX** [comment]
if u cant fix add me on skype slaserx@hotmail.com

**Comment by LiamKenyon** [comment]
TY, I fixed it but forgot to close the ticket.
