### ISSUE TITLE
links not working

### ISSUE THREAD

**Issue by Andy020** [SlaSerX/stalker#46]
links not working

after installation no stalker portal

**Comment by SlaSerX** [comment]
check logs

**Comment by Andy020** [comment]
this is what i got: --2019-09-24 19:33:44--  http://p.itbox.bg/tv/ministra-5.6.0.zip
Resolving p.itbox.bg (p.itbox.bg)... 5.104.177.220
Connecting to p.itbox.bg (p.itbox.bg)|5.104.177.220|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-09-24 19:33:44 ERROR 404: Not Found.

unzip:  cannot find or open ministra-5.6.0.zip, ministra-5.6.0.zip.zip or ministra-5.6.0.zip.ZIP.

**Comment by laser212** [comment]
I have the same thing tried to installl on ubuntu 14.04 and 16.04 no joy.

**Comment by SlaSerX** [comment]
add me on Skype: slaserx@hotmail.com
