### ISSUE TITLE
Smart Launcher Applications Do not install

### ISSUE THREAD

**Issue by pr3tty8oyfl0yd** [SlaSerX/stalker#47]
When i go to Applications > Smart Launcher Applications and choose any application and hit the install button no matter what app I install I get an error that says :

"Error! Unable to install application APP_NAME" 

Where APP_NAME is whatever app you are trying to install, so for example in this example it was Video_Club and I get the error "Error! Unable to install application magcore-app-video-club@2.14.0"

![image](https://user-images.githubusercontent.com/34938886/66638646-5359ac00-ebe3-11e9-97eb-3bb833ab9dbd.png)

**Server(please complete the following information):**
 - OS: Ubuntu 16.04
 - PHP 7
 - NPM: 2.15.11

This was a fresh install on a brand new VPS.

**Comment by Saentist** [comment]
Infomir have this problem from lot of time.

**Comment by SlaSerX** [comment]
i find solution just mkdir /var/www/.npm :)
