### ISSUE TITLE
mysql error during install ministra ubuntu 16.04 option

### ISSUE THREAD

**Issue by tkttkton** [SlaSerX/stalker#48]
mysql error during install ministra ubuntu 16.04 option:
ALTER TABLE `audio_compositions` ADD COLUMN `duration` INT DEFAULT 0; gave error
solved by modify /etc/mysql/my.cnf
[mysqld]
sql_mode = ""
#
# * Basic Settings
after install ok, erase line sql_mode ="" and restart mysql.

**Comment by tkttkton** [comment]
can you add to the script       set global sql_mode=""; so the build do not abort with the mysql version of ubuntu 16.04?

**Comment by SlaSerX** [comment]
build never abort for this maybe u have limitation on your vps
