### ISSUE TITLE
Looking For Custom Work (WILL PAY)

### ISSUE THREAD

**Issue by ptowns188** [SlaSerX/stalker#5]
Hi, I am looking to hire someone who has the skills to create me a script that will mass add all my TV Shows and Movies correctly to the Staalker/Ministra Portals Database.

If you can do what I need please reply here or add me on Skype using addy: scribe316

My email is also: paultowns188@gmail.com

Thanks

**Comment by SlaSerX** [comment]
Hello dear i can make all u want i add u also on skype

На 29.12.2017 г. 17:02 "ptowns188" <notifications@github.com> написа:

**Comment by satfun100** [comment]
Hi SlaSerX

I have been trying to contact you on Skype satfun100 I'm after this script too.

Please contact me.

Thanks

**Comment by satfun100** [comment]
SlaserX Why did you take my money and not deliver the script?
