### ISSUE TITLE
Links broken in install scrypt.

### ISSUE THREAD

**Issue by richiebob2015** [SlaSerX/stalker#52]
Tried 3 linux versions and all options.  Getting errors on install scrypt, url not resolved?

Please check

thanks :)

**Comment by richiebob2015** [comment]
invoke-rc.d: initscript nginx, action "start" failed.
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-04-07 15:32:51 UTC; 7ms ago
  Process: 23669 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=1/FAILURE)
  Process: 23664 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)

Apr 07 15:32:48 Newstalker systemd[1]: Starting A high performance web server and a reverse proxy server...
Apr 07 15:32:48 Newstalker nginx[23669]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 07 15:32:49 Newstalker nginx[23669]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 07 15:32:49 Newstalker nginx[23669]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 07 15:32:50 Newstalker nginx[23669]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 07 15:32:50 Newstalker nginx[23669]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 07 15:32:51 Newstalker nginx[23669]: nginx: [emerg] still could not bind()
Apr 07 15:32:51 Newstalker systemd[1]: nginx.service: Control process exited, code=exited status=1
Apr 07 15:32:51 Newstalker systemd[1]: Failed to start A high performance web server and a reverse proxy server.
Apr 07 15:32:51 Newstalker systemd[1]: nginx.service: Unit entered failed state.
Apr 07 15:32:51 Newstalker systemd[1]: nginx.service: Failed with result 'exit-code'.
dpkg: error processing package nginx-full (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up php7.0 (7.0.33-0ubuntu0.16.04.12) ...
Setting up php (1:7.0+35ubuntu6.1) ...
Setting up php7.0-mcrypt (7.0.33-0ubuntu0.16.04.12) ...

Creating config file /etc/php/7.0/mods-available/mcrypt.ini with new version
Setting up php-mcrypt (1:7.0+35ubuntu6.1) ...
Setting up php7.0-mysql (7.0.33-0ubuntu0.16.04.12) ...

Creating config file /etc/php/7.0/mods-available/mysqlnd.ini with new version

Creating config file /etc/php/7.0/mods-available/mysqli.ini with new version

Creating config file /etc/php/7.0/mods-available/pdo_mysql.ini with new version
Setting up php-mysql (1:7.0+35ubuntu6.1) ...
Setting up php7.0-xml (7.0.33-0ubuntu0.16.04.12) ...

Creating config file /etc/php/7.0/mods-available/dom.ini with new version

Creating config file /etc/php/7.0/mods-available/simplexml.ini with new version

Creating config file /etc/php/7.0/mods-available/wddx.ini with new version

Creating config file /etc/php/7.0/mods-available/xml.ini with new version

Creating config file /etc/php/7.0/mods-available/xmlreader.ini with new version

Creating config file /etc/php/7.0/mods-available/xmlwriter.ini with new version

Creating config file /etc/php/7.0/mods-available/xsl.ini with new version
Setting up php-xml (1:7.0+35ubuntu6.1) ...
Setting up php-pear (1:1.10.1+submodules+notgz-6ubuntu0.1) ...
Setting up ssl-cert (1.0.37) ...
Setting up nodejs (4.2.6~dfsg-1ubuntu4.2) ...
update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for systemd (229-4ubuntu21.27) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
Processing triggers for ufw (0.35-0ubuntu2) ...
Processing triggers for libapache2-mod-php7.0 (7.0.33-0ubuntu0.16.04.12) ...
Errors were encountered while processing:
 nginx-full
E: Sub-process /usr/bin/dpkg returned an error code (1)
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
E: Sub-process /usr/bin/dpkg returned an error code (1)
--2020-04-07 15:33:00--  http://itbox.bg/configs/000-default.conf
Resolving itbox.bg (itbox.bg)... 91.215.216.12
Connecting to itbox.bg (itbox.bg)|91.215.216.12|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-04-07 15:33:01 ERROR 403: Forbidden.

--2020-04-07 15:33:01--  http://itbox.bg/configs/ports.conf
Resolving itbox.bg (itbox.bg)... 91.215.216.12
Connecting to itbox.bg (itbox.bg)|91.215.216.12|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-04-07 15:33:01 ERROR 403: Forbidden.

--2020-04-07 15:33:01--  http://itbox.bg/configs/default
Resolving itbox.bg (itbox.bg)... 91.215.216.12
Connecting to itbox.bg (itbox.bg)|91.215.216.12|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-04-07 15:33:01 ERROR 403: Forbidden.

[....] Restarting apache2 (via systemctl): apache2.serviceJob for apache2.service failed because the control process exited with error code. See "systemctl status apache2.service" and "journalctl -xe" for details.
 failed!
[ ok ] Restarting nginx (via systemctl): nginx.service.

**Comment by Saentist** [comment]
You already have instaled someting on this PC.
Use fresh base server instalation only SSH instaled

**Comment by richiebob2015** [comment]
Im using a fresh vps image on digital ocean using ssh

still the same m8

anyideas?

thx :)

**Comment by richiebob2015** [comment]
Using a different fresh vps gets the same nginx and http error


Setting up nginx-full (1.10.3-0ubuntu0.16.04.5) ...
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
invoke-rc.d: initscript nginx, action "start" failed.
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-04-09 09:40:56 UTC; 28ms ago
  Process: 15181 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=1/FAILURE)
  Process: 15176 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)

Apr 09 09:40:53 stalker nginx[15181]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: A...se)
Apr 09 09:40:54 stalker nginx[15181]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: A...se)
Apr 09 09:40:54 stalker nginx[15181]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: A...se)
Apr 09 09:40:55 stalker nginx[15181]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: A...se)
Apr 09 09:40:55 stalker nginx[15181]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: A...se)
Apr 09 09:40:56 stalker nginx[15181]: nginx: [emerg] still could not bind()
Apr 09 09:40:56 stalker systemd[1]: nginx.service: Control process exited, code=exited ...s=1
Apr 09 09:40:56 stalker systemd[1]: Failed to start A high performance web server and a...er.
Apr 09 09:40:56 stalker systemd[1]: nginx.service: Unit entered failed state.
Apr 09 09:40:56 stalker systemd[1]: nginx.service: Failed with result 'exit-code'.
Hint: Some lines were ellipsized, use -l to show in full.
dpkg: error processing package nginx-full (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 nginx-full
E: Sub-process /usr/bin/dpkg returned an error code (1)
Module rewrite already enabled
E: Sub-process /usr/bin/dpkg returned an error code (1)
--2020-04-09 09:41:03--  http://itbox.bg/configs/000-default.conf
Resolving itbox.bg (itbox.bg)... 91.215.216.12
Connecting to itbox.bg (itbox.bg)|91.215.216.12|:80... connected.
HTTP request sent, awaiting response...

**Comment by SlaSerX** [comment]
try now i check it links works correct
