### ISSUE TITLE
Still does not work

### ISSUE THREAD

**Issue by richiebob2015** [SlaSerX/stalker#53]
Does not work with clean digital ocean image, ubuntu 16 / 18 with any config.

I can give you a fresh server to test, getiing nginx and apache2 error.

You said it was because of having something installed, but these are fresh / clean servers.  Also tried with a different host same problem.

Richiebob2013@gmail.com

I can give you the server to test anything u need.

Thanks

**Comment by SlaSerX** [comment]
Its work only on Ubuntu 16 clean add me on skype: slaserx@hotmail.com

На пн, 13.04.2020 г., 14:11 ч. richiebob2015 <notifications@github.com>
написа:
