### ISSUE TITLE
Stalker portal it does not work

### ISSUE THREAD

**Issue by canalpozuelo** [SlaSerX/stalker#56]
I have done a virtual machine installation with Ubuntu 14.04 stalker portal 5.2.0 installation and it seems that everything installs correctly but when I try to enter the browser at the address
http: // ip / stalker_portal / server / adm /
The screen remains blank and the login screen does not appear.

**Comment by SlaSerX** [comment]
maybe u wrong on any steps

**Comment by SlaSerX** [comment]
which options did u choice

**Comment by canalpozuelo** [comment]
In the stalker portal installation you are missing the download and decompression of the vendor file, where you have the autoload.php file

**Comment by SlaSerX** [comment]
on stalker portal u dont need vendor file :)

**Comment by SlaSerX** [comment]
script wor perfect i testet now

**Comment by canalpozuelo** [comment]
If you do not put the vendor file, the administration screen does not load you, the blank screen remains in mozilla and does not load. You copy the seller and it works perfectly
