### ISSUE TITLE
Suport Ubuntu 20.04

### ISSUE THREAD

**Issue by suricloud** [SlaSerX/stalker#57]
Hi,

Can you maybe update the install script so we can install ministra on ubuntu 20.04 ?

**Comment by Saentist** [comment]
Make virtual mashine with 16.04, else conect to Infomir to make support to newer PHP.

**Comment by SlaSerX** [comment]
its easy ubuntu 20 use php 7 u can make your own script for support ubuntu 20.04

**Comment by suricloud** [comment]
Can you please update your script that can support ubuntu 20.04 please.
Im not that expert to make a script :)
