### ISSUE TITLE
Errors in script

### ISSUE THREAD

**Issue by richiebob2013** [SlaSerX/stalker#59]
--2020-08-01 23:22:08--  http://p.itbox.bg/tv/ministra-5.6.1.zip
Resolving p.itbox.bg (p.itbox.bg)... 95.169.214.245
Connecting to p.itbox.bg (p.itbox.bg)|95.169.214.245|:80... failed: No route to host.
unzip:  cannot find or open ministra-5.6.1.zip, ministra-5.6.1.zip.zip or ministra-5.6.1.zip.ZIP.

May be other errors

**Comment by SlaSerX** [comment]
done i fix it check again
