### ISSUE TITLE
Facing issue while installing on Ubuntu 16.04 -  http://p.itbox.bg/tv/ministra-5.6.1.zip not accessable

### ISSUE THREAD

**Issue by hyaqoob** [SlaSerX/stalker#60]
Below is the log of the installation and it fails to setup 

Current default time zone: 'America/New_York'
Local time is now:      Sun Aug 23 15:07:00 EDT 2020.
Universal Time is now:  Sun Aug 23 19:07:00 UTC 2020.

mysql: [Warning] Using a password on the command line interface can be insecure.
[ ok ] Restarting mysql (via systemctl): mysql.service.
--2020-08-23 15:07:15--  http://p.itbox.bg/tv/ministra-5.6.1.zip
Resolving p.itbox.bg (p.itbox.bg)... 95.169.214.245
Connecting to p.itbox.bg (p.itbox.bg)|95.169.214.245|:80... failed: No route to host.
unzip:  cannot find or open ministra-5.6.1.zip, ministra-5.6.1.zip.zip or ministra-5.6.1.zip.ZIP.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
[ ok ] Restarting mysql (via systemctl): mysql.service.
./lab/ubuntu16: line 206: cd: /var/www/html/stalker_portal/admin: No such file or directory
--2020-08-23 15:07:19--  http://p.itbox.bg/tv/vendor.tar
Resolving p.itbox.bg (p.itbox.bg)... 95.169.214.245

Connecting to p.itbox.bg (p.itbox.bg)|95.169.214.245|:80... failed: No route to host.
tar: vendor.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
./lab/ubuntu16: line 212: cd: /var/www/html/stalker_portal/server: No such file or directory
--2020-08-23 15:07:20--  https://raw.githubusercontent.com/SlaSerX/stalker/master/docs/configs/custom.ini
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 251 [text/plain]
Saving to: ‘custom.ini’

custom.ini                   100%[==============================================>]     251  --.-KB/s    in 0s

2020-08-23 15:07:21 (4.08 MB/s) - ‘custom.ini’ saved [251/251]

--2020-08-23 15:07:21--  https://www.cloudflare.com/static/misc/mod_cloudflare/ubuntu/mod_cloudflare-trusty-amd64.latest.deb
Resolving www.cloudflare.com (www.cloudflare.com)... 104.17.210.9, 104.17.209.9, 2606:4700::6811:d209, ...
Connecting to www.cloudflare.com (www.cloudflare.com)|104.17.210.9|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-08-23 15:07:21 ERROR 404: Not Found.

dpkg-deb: error: '/tmp/mod_cloudflare-trusty-amd64.latest.deb' is not a debian format archive
dpkg: error processing archive /tmp/mod_cloudflare-trusty-amd64.latest.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /tmp/mod_cloudflare-trusty-amd64.latest.deb
sed: can't read /etc/apache2/mods-enabled/cloudflare.conf: No such file or directory
[ ok ] Restarting apache2 (via systemctl): apache2.service.
--2020-08-23 15:07:25--  https://files.phpmyadmin.net/phpMyAdmin/4.9.1/phpMyAdmin-4.9.1-all-languages.zip
Resolving files.phpmyadmin.net (files.phpmyadmin.net)... 185.76.9.13
Connecting to files.phpmyadmin.net (files.phpmyadmin.net)|185.76.9.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11349731 (11M) [application/zip]
Saving to: ‘phpMyAdmin-4.9.1-all-languages.zip’

phpMyAdmin-4.9.1-all-languag 100%[==============================================>]  10.82M  69.7MB/s    in 0.2s

2020-08-23 15:07:25 (69.7 MB/s) - ‘phpMyAdmin-4.9.1-all-languages.zip’ saved [11349731/11349731]

./lab/ubuntu16: line 236: cd: /var/www/html/stalker_portal/deploy: No such file or directory
Buildfile: build.xml does not exist!

[ + + + + + + + + + ] Press [Enter] to continue...

-----------------------------------------------------------------------

[ Install Complete Default username is: admin Default password is: 1 : ]

IP WAN       :XXXXXXXXX
Local IP     : 192.168.1.174
MySQL Pass   : st@lk3r
WEB          : http://192.168.1.174/stalker_portal
PHPMyadmin   : http://192.168.1.174/phpmyadmin

-----------------------------------------------------------------------

**Comment by richiebob2013** [comment]
Same problem over here :(

**Comment by SlaSerX** [comment]
Links updated
