### ISSUE TITLE
500 Internal Server Error  on some of the menu's

### ISSUE THREAD

**Issue by liors1111** [SlaSerX/stalker#62]
**Describe the bug**
hello, 
i have some issue with some of the menu's : example l try to go in the  Movie list , i got 500 Internal Server Error  XHRGEThttp://x.x.x.x/stalker_portal/server/adm/new-video-club/video-list-json? draw=1&columns%5B0.........
[HTTP/1.1 500 Internal Server Error 225ms]

also when i try to edit tv-channels i got: 	500 Internal Server Error

 http://x.x.x.x/stalker_portal/server/adm/tv-channels/edit-channel

i using a linux ubantu 16.04.07 LTS
can you help on this one?
thanks

**Comment by SlaSerX** [comment]
check web server logs
