### ISSUE TITLE
Cloudflare module is not installed 

### ISSUE THREAD

**Issue by Web-Guy-Sh** [SlaSerX/stalker#63]
https://www.cloudflare.com/static/misc/mod_cloudflare/ubuntu/mod_cloudflare-trusty-amd64.latest.deb

returns 404

Hopefully, there is another way to download that module

**Comment by SlaSerX** [comment]
Thx

На вт, 27.10.2020 г. в 19:26 GurrpreetDhaliwal <notifications@github.com>
написа:

**Comment by SlaSerX** [comment]
i will fix that
