### ISSUE TITLE
PHING EXECUTION FAILS ON UBUNTU 16.04

### ISSUE THREAD

**Issue by d3rmey** [SlaSerX/stalker#67]
Due to composer repositories have been updated, phing execution during the Ministra deployment might fail on Ubuntu 16.04
***************************************************************************
https://wiki.infomir.eu/eng/ministra-tv-platform/ministra-installation-guide/faq/what-to-do-if-phing-execution-fails-on-ubuntu-16-04
*******************************************************************************
The "ocramius/package-versions" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.
 
  Problem 1
    - ocramius/package-versions is locked to version 1.2.0 and an update of this package was not requested.
    - ocramius/package-versions 1.2.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - ocramius/package-versions 1.2.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - ocramius/proxy-manager 2.0.4 requires ocramius/package-versions ^1.0 -> satisfiable by ocramius/package-versions[1.2.0].
    - ocramius/proxy-manager is locked to version 2.0.4 and an update of this package was not requested.
 
ocramius/package-versions only provides support for Composer 2 in 1.8+, which requires PHP 7.4.
If you can not upgrade PHP you can require composer/package-versions-deprecated to resolve this with PHP 7.0+.
 
You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

**************************** 
To avoid this, it is needed to use composer version 1.9.1.

1. Download the patch composer_version_1.9.1.patch inside the Ministra directory (stalker_portal by default) and apply it to the deploy/build.xml file

sudo patch -p0 < composer_version_1.9.1.patch

2. Run phing to complete the build

**Comment by SlaSerX** [comment]
all its work for me try to patch composer
