### ISSUE TITLE
install on debian 8 is not working

### ISSUE THREAD

**Issue by shdf2** [SlaSerX/stalker#68]
hello,
just tried the auto install script on a fresh **debian 8 netinstall iso**.
1, during the installation it doesn't find the "locale en_us.utf-8"
2, at the end it asks for the mysql pass, which i guess is **st@lk3r** and then display the link http://ip_address/stalker_portal to access the panel which is not working, it shows **error 500** in the browser.
3, i can see that apache is working when i go to http://ip_address

**Comment by shdf2** [comment]
so closed without answer. nice support.

**Comment by SlaSerX** [comment]
Its automatet close when dont have answer of the new release all f the
script wikk be worked today new release will be avalible

На чт, 4.02.2021 г., 13:16 shdf2 <notifications@github.com> написа:

**Comment by SlaSerX** [comment]
Also new release not be free

На чт, 4.02.2021 г., 13:18 Ivan Bachvarov <slaserx3@gmail.com> написа:
