### ISSUE TITLE
I want to install this on existing ubuntu server.

### ISSUE THREAD

**Issue by nileshlets** [SlaSerX/stalker#7]
Hello, 
I have one ubuntu server on which I am running multiple node applications right now.
Now I want to install stalker on this server. Is this possible or I have to purchase new fresh server to install this as per your read me file ( _Script work only on Clean Debian/Ubuntu install servers_ ) ?.
Please advise.

**Comment by SlaSerX** [comment]
Hello if u want use my autoinstall script u need clean server if u want
install manual u can use your old server and need make any changes for can
work correctly.

На 5.01.2018 г. 8:09 "Nilesh Panchal" <notifications@github.com> написа:

**Comment by nileshlets** [comment]
Can you guide me how to install stalker manually? Any steps or guide available?

**Comment by SlaSerX** [comment]
Nope dont work that command is only for new and auto installation if u want to install manual just givme your skype or watssup

**Comment by SlaSerX** [comment]
givme your skype and told me when u online

2018-01-08 10:49 GMT+02:00 Nilesh Panchal <notifications@github.com>:

**Comment by nileshlets** [comment]
Hi my skype is nilesh.panchal@cre8ivelabs.com. I am online from 10 AM to 8 PM IST.
