### ISSUE TITLE
Various issues on fresh Debian 9 server

### ISSUE THREAD

**Issue by BlackTiger63** [SlaSerX/stalker#8]
I would like to install this on a fresh Debian 9 server but several errors occur.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php5-mysql is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package upstart is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  sysvinit-core systemd-sysv

E: Package 'php5' has no installation candidate
E: Package 'php5-mysql' has no installation candidate
E: Package 'upstart' has no installation candidate
Adding Channel "pear.phing.info" succeeded
Discovery of channel "pear.phing.info" succeeded
WARNING: "pear/PEAR_PackageFileManager" is deprecated in favor of "pear/PEAR_PackageFileManager2"
Unknown remote channel: pear.pdepend.org
Unknown remote channel: pear.phpmd.org
Unknown remote channel: pear.phpdoc.org
Did not download optional dependencies: phing/phingdocs, pear/VersionControl_SVN, pear/VersionControl_Git, pecl/Xdebug, pear/PEAR_PackageFileManager, pear/Services_Amazon_S3, pear/HTTP_Request2, channel://pear.pdepend.org/PHP_Depend, channel://pear.phpmd.org/PHP_PMD, channel://pear.phpdoc.org/phpDocumentor, pear/PHP_CodeSniffer, pear/Net_Growl, use --alldeps to download automatically

Current default time zone: 'Europe/Berlin'
Local time is now:      Tue Jan 23 15:27:08 CET 2018.
Universal Time is now:  Tue Jan 23 14:27:08 UTC 2018.

./install: line 53: cd: /var/www/html/: No such file or directory
```

Some errors like this during Ministra install:
./install: line 62: /etc/php5/apache2/php.ini: No such file or directory
./install: line 63: a2enmod: command not found
E: Unable to locate package libapache2-mod-php5filter
./install: line 66: cd: /etc/apache2/sites-enabled/: No such file or directory

And after the ministra install:
./install: line 75: /etc/init.d/apache2: No such file or directory
./install: line 76: /etc/init.d/nginx: No such file or directory
./install: line 77: /etc/init.d/apache2: No such file or directory
./install: line 78: /etc/init.d/nginx: No such file or directory
./install: line 80: cd: /var/www/html/stalker_portal/deploy: No such file or directory
Buildfile: build.xml does not exist!

So it looks as several things are not installed. I can reformat if necessary.

How can I fix this?

**Comment by SlaSerX** [comment]
For now u can install on Debian 9 not with auto install script u can
install manual :)


2018-01-23 16:35 GMT+02:00 Black Tiger <notifications@github.com>:

**Comment by BlackTiger63** [comment]
Ah pity, oke thank you.
